### ISSUE TITLE
New thresholds for n-year storms

### ISSUE THREAD

**Issue by kbrose** [NORCatUofC/rain#13]
Is it possible to re-create the analysis done in bulletin 70 (http://www.isws.illinois.edu/atmos/statecli/RF/download.htm) to determine what the new thresholds are for an n-year storm? Not necessarily to re-create all of the research (probably only interested in the Northeast "Climatic section" since that contains Chicago, and probably not all "durations"),

For reference, these are the current definitions:

```
       1-year   2-year  5-year  10-year 25-year 50-year 100-year
Duration                            
10-day  4.12    4.95    6.04    6.89    8.18    9.38    11.14
5-day   3.25    3.93    4.91    5.70    6.93    8.04    9.96
72-hr   2.93    3.55    4.44    5.18    6.32    7.41    8.78
48-hr   2.70    3.30    4.09    4.81    5.88    6.84    8.16
24-hr   2.51    3.04    3.80    4.47    5.51    6.46    7.58
18-hr   2.30    2.79    3.50    4.11    5.06    5.95    6.97
12-hr   2.18    2.64    3.31    3.89    4.79    5.62    6.59
6-hr    1.88    2.28    2.85    3.35    4.13    4.85    5.68
3-hr    1.60    1.94    2.43    2.86    3.53    4.14    4.85
2-hr    1.48    1.79    2.24    2.64    3.25    3.82    4.47
1-hr    1.18    1.43    1.79    2.10    2.59    3.04    3.56
30-min  0.93    1.12    1.41    1.65    2.04    2.39    2.80
15-min  0.68    0.82    1.03    1.21    1.49    1.75    2.05
10-min  0.55    0.67    0.84    0.98    1.21    1.42    1.67
5-min   0.30    0.36    0.46    0.54    0.66    0.78    0.91
```

And in plot form:

![index](https://cloud.githubusercontent.com/assets/4053170/18497486/41f22154-79f4-11e6-86cd-12eb0ea05f4f.png)

**Comment by kbrose** [comment]
From bulletin 70:

>    As in any statistical analysis, the individual ob-
>     servations or data points should be independent of
>     each  other.  With  a  partial-duration  series,  one  must
>     be careful that the observations used are not meteor-
>     ologically  dependent;  that  is,  they  must  be  from  sepa-
>     rate storm systems. In the present study, data for
>     precipitation  durations  of  24  hours  or  less  were  ob-
>     tained  from  individual  precipitation  events,  defined
>     as  precipitation  periods  in  which  there  was  no  pre-
>     cipitation  for  at  least  6  hours  before  and  6  hours
>     after  the  precipitation  event (Huff, 1967);  then,  only
>     the maximum value for the particular duration (6
>     hours,  12  hours,  etc.)  within  such  a  precipitation
>     event  was  used.  This  ensures  that  the  precipitation
>     values are independent of each other and are derived
>     from  individual  storms.  For  precipitation  durations
>     of 2 to 10 days, no time separation criteria were
>     needed.

This seems incomplete to me. How would we handle aggregating daily values into 48 hour chunks (or worse, hourly data to 48 hour chunks)? Consider the following:

```
day, rainfall
1,   0
2,   1.5
3,   3.5
4,   2.5
5,   0
6,   0
```

If we combine days such that 1 and 2 are aggregated, we get a different max value than if we aggregate 2 and 3. If we aggregate both 1 and 2 **_and**_ 2 and 3, then we do not have independent values...

On the plus side, apart from this issue it looks like it should be fairly reproducible. We won't have quite as much historical data as the original analysis, but hopefully it'll be enough to come to some conclusions...

**Comment by sbeslow** [comment]
Just to clarify what this means -- if we are looking at 24 hours where there are no 6 hour gaps in rainfall, then there can only be 1 n-year storm in that range even if there is no overlap in two periods that cross the thresholds.  Is this right?

**Comment by kbrose** [comment]
Correct, if you have 48 straight hours of rain, then that entire chunk can only be counted once towards an n-year storm for durations <= 24 hours.

Seems kind of arbitrary since we don't do the same for 48 hours or more, but maybe talking about storms of <= 24 hours is viewed as a different kind of thing from lots of rain over >= 48 hours.

Regardless, it's not the way I would have defined it. To me, taking the fraction

```
all consecutive windows of a given duration with rainfall above some threshold T
--------------------------------------------------------------------------------
         the total number of consecutive windows of the given duration
```

(the denominator is easily convertible into "years") is more in line with what I was thinking. _Then_ you can use the recurrence interval to answer the question "for any window of time with a given duration, what's the probability that it will rain more than `T` inches?" I believe this question is un-answerable in the given formulation.
