### ISSUE TITLE
Map of 311 calls about flooded street and basement (links)

### ISSUE THREAD

**Issue by dbild** [NORCatUofC/rain#2]
Here is the pdf from the city with a map showing 311 requests (pg. 16 has the map; pg. 6-8 discusses data sources including 311 calls) Pg. 8 states: "The City tracks two types of calls to 311 related to flooding: water-in-basement and water-in-street"
http://www.cityofchicago.org/content/dam/city/depts/obm/general/SubstantialAmendment2015%20FOR%20PUBLIC%20COMMENT.pdf

Also a much longer document about the Community Development Block Grant http://www.cityofchicago.org/content/dam/city/depts/obm/supp_info/CDBG/Jan2015_HUD_Approved_Substantial_Amendment.pdf

**Comment by pjsier** [comment]
Closing because FOIA received, referenced in #3
